language: ruby
rvm:
  - '2.3.1'
before_script:
  - export TEASPOON_DRIVER=phantomjs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - bundle install
script: bundle exec rake ci
